import logging

CALIBRATION_FILE = "calibration.json"

# ModuleManager
MODULEMANAGER_MAX_TERM_TIME = 2

# Interfaces
CAMERA_INDEX = 2
CAMERA_MOUNT_ANGLE = 25
# CAMERA_MOUNT_POSITION = (0, 50, 73) # bottom camera
CAMERA_MOUNT_POSITION = (0, 0, 135)
CAMERA_FRAMEBUFFER_SIZE = 1024 * 256
CAMERA_ENCODE_QUALITY = 90 # From O to 100 (%)

UNDERCARRIAGE_SERIAL_PORT = "/dev/ttyAMA1"
UNDERCARRIAGE_BOUD_RATE = 115200
SENSOR_ANGLES = [ # Angles of sensors from front center, clockwise
    10.9, 30.6, 66, 83,
    99.3, 114, 155.8, 170.5,
    191, 204, 246, 261.5,
    279.2, 294, 329.8, 348.4
]
SENSOR_MAX_DIST = 81.5
SENSOR_DIST = [55, 65] + [SENSOR_MAX_DIST for _ in range(len(SENSOR_ANGLES)-4)] + [65, 55] # Distances from center

SENSOR_THRES = 550

COMPASS_SERIAL_PORT = "/dev/ttyAMA2"
COMPASS_READ_ACC = False
COMPASS_INIT_ATTEMPTS = 5
COMPASS_INIT_DELAY = 0.1

DISPLAY_I2C_BUS = 3
DISPLAY_I2C_ADDR = 0x3c
DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 32
DISPLAY_WIFI_ICON = "soccer_robot/assets/ui/wifi.png"
DISPLAY_DEBUG_ICON = "soccer_robot/assets/ui/debug.png"
DISPLAY_BTH_ICON = "soccer_robot/assets/ui/bluetooth.png"
DISPLAY_FONT = None
DISPLAY_FPS = 10
DISPLAY_CIRCLE_D = 20
DISPLAY_CIRCLE_E = 1.1

UI_WIFI_INTERVAL = 2
UI_IP_INTERVAL = 5
UI_MAX_STATUS = 24

BUTTON_MOTORS_PIN = 10
BUTTON_MOTORS_BOUNCE = None

# Logging
LOGGER_MAX_QUEUE_SIZE = 10
LOGGER_LOGS_PATH = "."
LOGGER_CONSOLE_LOGLEVEL = logging.INFO
LOGGER_FILE_LOGLEVEL = logging.DEBUG

# Visualization
VISUALIZER_PORT = 8765
VISUALIZER_MESSAGE_INTERVAL = 0.06
VISUALIZE_IMAGE_WIDTH = 640
VISUALIZE_IMAGE_HEIGHT = 480

# Communication
BTH_SERVER_INDEX = 0
BTH_POWERUP_ADAPTER = True
BTH_MESSAGE_INTERVAL = 60
BTH_RECONNECT_INTERVAL = 1000

# Robot
ROBOT_PRECISE_BALL_MOVE = True
ROBOT_DEFEND = True

ROBOT_SPIN_OFFSET_SMALL = 0.015
ROBOT_SPIN_OFFSET_BIG = 0.025

#ROBOT_SPEED = 80
#ROBOT_SHOOTING_SPEED = 90
#ROBOT_ROTATING_SPEED = 60
#ROBOT_BACKWARDS_SPEED = ROBOT_SPEED
ROBOT_BACKWARDS_TIME = 1000
ROBOT_WHEEL_D = 50

MOTOR_CONF = 2
MOTOR_SPEED_TO_RPM = 500/255

LINE_AVOID_FAST_THRES = 125
LINE_AVOID_FAST = 800
LINE_AVOID_SLOW = 150
#LINE_AVOID_SPEED = ROBOT_SPEED
LINE_AVOID_ANTIVECTOR = 1.8

BALL_TARGET_DISTANCE = 270
BALL_DIAMETER = 42
GOAL_REAL_SIZE = (600, 120) # Resize to 100 before competition!!!
GOAL_POSITION = (0, 1100)
BALL_MIN_SIZE = (0.01, 0.01)
GOAL_MIN_SIZE = (0.1, 0.02)
GOAL_HEIGHT_SAMPLE = 1/4

BALL_FINDING_ROTATE_TIME = 400
BALL_FINDING_WAIT_TIME = 100

SPIN_MAX_SPEED_ANGLE = 80

SPIN_SHOOTPOS_SPEED = 0.20 # when going to shooting position
SPIN_BALL_SPEED = 0.30 # when going from shooting position to ball
SPIN_GOAL_SPEED = 0.2 # when going from ball to goal
SPIN_BACKWARDS_SPEED = 0.18 # when going backwards to find a ball
SPIN_GET_AROUND_SPEED = 0.35 # when getting around ball

GET_AROUND_ANGLE = 30
GET_AROUND_MIN_DIST = 250
GET_AROUND_MAX_DIST = 400

GET_AROUND_MID_DIST = 250
GET_AROUND_MIN_SPEED_MULT = 0.75
GET_AROUND_MAX_BALL_ANGLE = 35
GET_AROUND_ROTATE_SPEED = 60

GOALIE_MASTER_INDEX = 0
GOALIE_CHANGE_TIME = 2000
BACK_OFF_SECTOR = 7
BACK_OFF_OK_SECTORS = [6, 7, 8]
BACK_OFF_SPIN = 0.6

FIELD_SIZE = (1580, 2190)
TRACKER_HEATMAP_WIDTH = 3
TRACKER_HEATMAP_POINTS = [(x, y) for y in [745, 0, -1100] for x in [-595, 0, 595]]
TRACKER_HEATMAP_LINES = [
    ['l', 'u'], ['u'], ['r', 'u'],
    ['l'], [], ['r'],
    ['l', 'd'], ['d'], ['r', 'd']
]
TRACKER_LINE_SIGNS = ['u', 'r', 'd', 'l']

TRACKER_GOAL_SPOT_R = 700
TRACKER_MIN_MOVE = 200
TRACKER_LINE_ADDEND = 0.01
TRACKER_LINE_MULTIPLIER = 1.2
